name: "Submodule Test"
description: ""

runs:
  using: "composite"
  steps:
    - name: execute test
      shell: python
      run: |
        from os import path, env
        path = rf"{env['github.action_path']}\submodule\test.txt"
        print(path)
        print(path.exists(path))
