name: "Submodule Test"
description: ""

runs:
  using: "composite"
  steps:
    - name: execute test
      shell: python
      run: |
        from os import path, environ
        path_str = rf"{environ['ACTION_PATH']}\submodule\test.txt"
        print(path_str)
        print(path.exists(path_str))
      env:
        ACTION_PATH: $(( github.action_path ))
